import "server-only";

import { type BundledLanguage, codeToHtml } from "shiki";

import { cn } from "@/lib/utils";

type CodeBlockProps = {
  className?: string;
  code: string;
  fileName?: string;
  language?: BundledLanguage;
  showLineNumbers?: boolean;
};

export async function CodeBlock({
  className,
  code,
  fileName = "snippet.ts",
  language = "ts",
  showLineNumbers = true,
}: CodeBlockProps) {
  const highlightedCode = await codeToHtml(code, {
    lang: language,
    theme: "vesper",
  });

  const lineCount = Math.max(1, code.split(/\r\n|\r|\n/).length);

  return (
    <div
      className={cn(
        "w-full max-w-140 border border-border-primary bg-bg-input",
        className,
      )}
    >
      <div className="flex h-10 items-center gap-3 border-b border-border-primary px-4">
        <span className="size-2.5 rounded-full bg-[#EF4444]" />
        <span className="size-2.5 rounded-full bg-[#F59E0B]" />
        <span className="size-2.5 rounded-full bg-[#10B981]" />
        <span className="h-px flex-1" />
        <span className="font-mono text-xs text-text-tertiary">{fileName}</span>
      </div>

      <div className="flex">
        {showLineNumbers ? (
          <div className="flex w-10 flex-col items-end gap-1.5 border-r border-border-primary bg-bg-surface px-2.5 py-3">
            {Array.from({ length: lineCount }).map((_, index) => (
              <span
                className="font-mono text-[13px] text-text-tertiary"
                key={`line-number-${index + 1}`}
              >
                {index + 1}
              </span>
            ))}
          </div>
        ) : null}

        <div
          className="min-w-0 flex-1 overflow-x-auto [&_code]:font-mono [&_pre]:m-0! [&_pre]:bg-transparent! [&_pre]:p-3!"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: trusted HTML generated by Shiki on server
          dangerouslySetInnerHTML={{ __html: highlightedCode }}
        />
      </div>
    </div>
  );
}
